version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: campus-guide-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: campus_guide
      MYSQL_USER: campus_user
      MYSQL_PASSWORD: campus_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - campus-network
    restart: unless-stopped

  # Redis缓存 (可选)
  redis:
    image: redis:7-alpine
    container_name: campus-guide-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - campus-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # 主应用
  app:
    build: .
    container_name: campus-guide-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/campus_guide
      - SPRING_DATASOURCE_USERNAME=campus_user
      - SPRING_DATASOURCE_PASSWORD=campus_password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - campus-network
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads

volumes:
  mysql_data:
  redis_data:
  app_logs:
  app_uploads:

networks:
  campus-network:
    driver: bridge