server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: campus-guide
  
  datasource:
    url: jdbc:mysql://mysql:3306/campus_guide?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:campus_user}
    password: ${SPRING_DATASOURCE_PASSWORD:campus_password}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  # Redis配置 (可选)
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myProductionSecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# File Upload Configuration
file:
  upload:
    path: ${FILE_UPLOAD_PATH:/app/uploads/}
    max-size: 10485760 # 10MB

# Logging Configuration
logging:
  level:
    com.university.campusguide: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: /app/logs/campus-guide.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized